Revert "Update deps", fix prod
This reverts commit 4ff1f32123cbda64c4d9d95c64cceef92a102e9c.

```
error: Cannot find module '../../../../src/common/abstractRefiners' from '/app/node_modules/chrono-node/dist/esm/locales/ja/refiners/JPMergeWeekdayComponentRefiner.js'
```